// Productos del catálogo BeaGi ModaCircular
// Para modificar el catálogo, cambia los datos de este archivo.

const productosBeaGi = [
    {
        "id": 1,
        "nombre": "Abrigo Beige Clásico",
        "tipo": "Abrigo de Paño",
        "talla": "M",
        "estado": "Excelente estado",
        "precio": 25000,
        "disponibilidad": "Disponible",
        "imagen": "",
        "descripcion": "Abrigo elegante y versátil, ideal para outfits de invierno.",
        "destacado": true
    },
    {
        "id": 2,
        "nombre": "Abrigo Negro Elegante",
        "tipo": "Abrigo Largo",
        "talla": "L",
        "estado": "Muy buen estado",
        "precio": 28000,
        "disponibilidad": "Disponible",
        "imagen": "",
        "descripcion": "Abrigo negro formal, perfecto para uso diario o eventos.",
        "destacado": true
    },
    {
        "id": 3,
        "nombre": "Abrigo Café Casual",
        "tipo": "Abrigo Urbano",
        "talla": "S",
        "estado": "Buen estado",
        "precio": 22000,
        "disponibilidad": "Disponible",
        "imagen": "",
        "descripcion": "Abrigo cómodo, combinable y con estilo casual.",
        "destacado": false
    },
    {
        "id": 4,
        "nombre": "Abrigo de Lana 4",
        "tipo": "Abrigo de Lana",
        "talla": "S",
        "estado": "Excelente estado",
        "precio": 22000,
        "disponibilidad": "Disponible",
        "imagen": "",
        "descripcion": "Espacio reservado para abrigo de lana. Aquí luego agregaremos foto real, color, medidas y detalles.",
        "destacado": false
    },
    {
        "id": 5,
        "nombre": "Trench Coat 5",
        "tipo": "Trench Coat",
        "talla": "M",
        "estado": "Muy buen estado",
        "precio": null,
        "disponibilidad": "Disponible",
        "imagen": "",
        "descripcion": "Espacio reservado para trench coat. Aquí luego agregaremos foto real, color, medidas y detalles.",
        "destacado": false
    },
    {
        "id": 6,
        "nombre": "Abrigo Teddy 6",
        "tipo": "Abrigo Teddy",
        "talla": "L",
        "estado": "Buen estado",
        "precio": 24000,
        "disponibilidad": "Disponible",
        "imagen": "",
        "descripcion": "Espacio reservado para abrigo teddy. Aquí luego agregaremos foto real, color, medidas y detalles.",
        "destacado": false
    },
    {
        "id": 7,
        "nombre": "Parka Larga 7",
        "tipo": "Parka Larga",
        "talla": "XL",
        "estado": "Por revisar",
        "precio": 25000,
        "disponibilidad": "Reservado",
        "imagen": "",
        "descripcion": "Espacio reservado para parka larga. Aquí luego agregaremos foto real, color, medidas y detalles.",
        "destacado": true
    },
    {
        "id": 8,
        "nombre": "Abrigo Oversize 8",
        "tipo": "Abrigo Oversize",
        "talla": "S",
        "estado": "Excelente estado",
        "precio": 26000,
        "disponibilidad": "Disponible",
        "imagen": "",
        "descripcion": "Espacio reservado para abrigo oversize. Aquí luego agregaremos foto real, color, medidas y detalles.",
        "destacado": false
    },
    {
        "id": 9,
        "nombre": "Gabardina 9",
        "tipo": "Gabardina",
        "talla": "M",
        "estado": "Muy buen estado",
        "precio": 27000,
        "disponibilidad": "Disponible",
        "imagen": "",
        "descripcion": "Espacio reservado para gabardina. Aquí luego agregaremos foto real, color, medidas y detalles.",
        "destacado": false
    },
    {
        "id": 10,
        "nombre": "Chaquetón 10",
        "tipo": "Chaquetón",
        "talla": "L",
        "estado": "Buen estado",
        "precio": null,
        "disponibilidad": "Disponible",
        "imagen": "",
        "descripcion": "Espacio reservado para chaquetón. Aquí luego agregaremos foto real, color, medidas y detalles.",
        "destacado": false
    },
    {
        "id": 11,
        "nombre": "Abrigo de Paño 11",
        "tipo": "Abrigo de Paño",
        "talla": "XL",
        "estado": "Por revisar",
        "precio": 29000,
        "disponibilidad": "Disponible",
        "imagen": "",
        "descripcion": "Espacio reservado para abrigo de paño. Aquí luego agregaremos foto real, color, medidas y detalles.",
        "destacado": false
    },
    {
        "id": 12,
        "nombre": "Blazer Largo 12",
        "tipo": "Blazer Largo",
        "talla": "S",
        "estado": "Excelente estado",
        "precio": 30000,
        "disponibilidad": "Disponible",
        "imagen": "",
        "descripcion": "Espacio reservado para blazer largo. Aquí luego agregaremos foto real, color, medidas y detalles.",
        "destacado": false
    },
    {
        "id": 13,
        "nombre": "Abrigo Peludo 13",
        "tipo": "Abrigo Peludo",
        "talla": "M",
        "estado": "Muy buen estado",
        "precio": 31000,
        "disponibilidad": "Vendido",
        "imagen": "",
        "descripcion": "Espacio reservado para abrigo peludo. Aquí luego agregaremos foto real, color, medidas y detalles.",
        "destacado": false
    },
    {
        "id": 14,
        "nombre": "Abrigo de Lana 14",
        "tipo": "Abrigo de Lana",
        "talla": "L",
        "estado": "Buen estado",
        "precio": 32000,
        "disponibilidad": "Reservado",
        "imagen": "",
        "descripcion": "Espacio reservado para abrigo de lana. Aquí luego agregaremos foto real, color, medidas y detalles.",
        "destacado": true
    },
    {
        "id": 15,
        "nombre": "Trench Coat 15",
        "tipo": "Trench Coat",
        "talla": "XL",
        "estado": "Por revisar",
        "precio": null,
        "disponibilidad": "Disponible",
        "imagen": "",
        "descripcion": "Espacio reservado para trench coat. Aquí luego agregaremos foto real, color, medidas y detalles.",
        "destacado": false
    },
    {
        "id": 16,
        "nombre": "Abrigo Teddy 16",
        "tipo": "Abrigo Teddy",
        "talla": "S",
        "estado": "Excelente estado",
        "precio": 34000,
        "disponibilidad": "Disponible",
        "imagen": "",
        "descripcion": "Espacio reservado para abrigo teddy. Aquí luego agregaremos foto real, color, medidas y detalles.",
        "destacado": false
    },
    {
        "id": 17,
        "nombre": "Parka Larga 17",
        "tipo": "Parka Larga",
        "talla": "M",
        "estado": "Muy buen estado",
        "precio": 35000,
        "disponibilidad": "Disponible",
        "imagen": "",
        "descripcion": "Espacio reservado para parka larga. Aquí luego agregaremos foto real, color, medidas y detalles.",
        "destacado": false
    },
    {
        "id": 18,
        "nombre": "Abrigo Oversize 18",
        "tipo": "Abrigo Oversize",
        "talla": "L",
        "estado": "Buen estado",
        "precio": 36000,
        "disponibilidad": "Disponible",
        "imagen": "",
        "descripcion": "Espacio reservado para abrigo oversize. Aquí luego agregaremos foto real, color, medidas y detalles.",
        "destacado": false
    },
    {
        "id": 19,
        "nombre": "Gabardina 19",
        "tipo": "Gabardina",
        "talla": "XL",
        "estado": "Por revisar",
        "precio": 37000,
        "disponibilidad": "Disponible",
        "imagen": "",
        "descripcion": "Espacio reservado para gabardina. Aquí luego agregaremos foto real, color, medidas y detalles.",
        "destacado": false
    },
    {
        "id": 20,
        "nombre": "Chaquetón 20",
        "tipo": "Chaquetón",
        "talla": "S",
        "estado": "Excelente estado",
        "precio": null,
        "disponibilidad": "Disponible",
        "imagen": "",
        "descripcion": "Espacio reservado para chaquetón. Aquí luego agregaremos foto real, color, medidas y detalles.",
        "destacado": false
    },
    {
        "id": 21,
        "nombre": "Abrigo de Paño 21",
        "tipo": "Abrigo de Paño",
        "talla": "M",
        "estado": "Muy buen estado",
        "precio": 39000,
        "disponibilidad": "Reservado",
        "imagen": "",
        "descripcion": "Espacio reservado para abrigo de paño. Aquí luego agregaremos foto real, color, medidas y detalles.",
        "destacado": true
    },
    {
        "id": 22,
        "nombre": "Blazer Largo 22",
        "tipo": "Blazer Largo",
        "talla": "L",
        "estado": "Buen estado",
        "precio": 40000,
        "disponibilidad": "Disponible",
        "imagen": "",
        "descripcion": "Espacio reservado para blazer largo. Aquí luego agregaremos foto real, color, medidas y detalles.",
        "destacado": false
    },
    {
        "id": 23,
        "nombre": "Abrigo Peludo 23",
        "tipo": "Abrigo Peludo",
        "talla": "XL",
        "estado": "Por revisar",
        "precio": 41000,
        "disponibilidad": "Disponible",
        "imagen": "",
        "descripcion": "Espacio reservado para abrigo peludo. Aquí luego agregaremos foto real, color, medidas y detalles.",
        "destacado": false
    },
    {
        "id": 24,
        "nombre": "Abrigo de Lana 24",
        "tipo": "Abrigo de Lana",
        "talla": "S",
        "estado": "Excelente estado",
        "precio": 42000,
        "disponibilidad": "Disponible",
        "imagen": "",
        "descripcion": "Espacio reservado para abrigo de lana. Aquí luego agregaremos foto real, color, medidas y detalles.",
        "destacado": false
    },
    {
        "id": 25,
        "nombre": "Trench Coat 25",
        "tipo": "Trench Coat",
        "talla": "M",
        "estado": "Muy buen estado",
        "precio": null,
        "disponibilidad": "Disponible",
        "imagen": "",
        "descripcion": "Espacio reservado para trench coat. Aquí luego agregaremos foto real, color, medidas y detalles.",
        "destacado": false
    },
    {
        "id": 26,
        "nombre": "Abrigo Teddy 26",
        "tipo": "Abrigo Teddy",
        "talla": "L",
        "estado": "Buen estado",
        "precio": 44000,
        "disponibilidad": "Vendido",
        "imagen": "",
        "descripcion": "Espacio reservado para abrigo teddy. Aquí luego agregaremos foto real, color, medidas y detalles.",
        "destacado": false
    },
    {
        "id": 27,
        "nombre": "Parka Larga 27",
        "tipo": "Parka Larga",
        "talla": "XL",
        "estado": "Por revisar",
        "precio": 45000,
        "disponibilidad": "Disponible",
        "imagen": "",
        "descripcion": "Espacio reservado para parka larga. Aquí luego agregaremos foto real, color, medidas y detalles.",
        "destacado": false
    },
    {
        "id": 28,
        "nombre": "Abrigo Oversize 28",
        "tipo": "Abrigo Oversize",
        "talla": "S",
        "estado": "Excelente estado",
        "precio": 46000,
        "disponibilidad": "Reservado",
        "imagen": "",
        "descripcion": "Espacio reservado para abrigo oversize. Aquí luego agregaremos foto real, color, medidas y detalles.",
        "destacado": true
    },
    {
        "id": 29,
        "nombre": "Gabardina 29",
        "tipo": "Gabardina",
        "talla": "M",
        "estado": "Muy buen estado",
        "precio": 47000,
        "disponibilidad": "Disponible",
        "imagen": "",
        "descripcion": "Espacio reservado para gabardina. Aquí luego agregaremos foto real, color, medidas y detalles.",
        "destacado": false
    },
    {
        "id": 30,
        "nombre": "Chaquetón 30",
        "tipo": "Chaquetón",
        "talla": "L",
        "estado": "Buen estado",
        "precio": null,
        "disponibilidad": "Disponible",
        "imagen": "",
        "descripcion": "Espacio reservado para chaquetón. Aquí luego agregaremos foto real, color, medidas y detalles.",
        "destacado": false
    },
    {
        "id": 31,
        "nombre": "Abrigo de Paño 31",
        "tipo": "Abrigo de Paño",
        "talla": "XL",
        "estado": "Por revisar",
        "precio": 49000,
        "disponibilidad": "Disponible",
        "imagen": "",
        "descripcion": "Espacio reservado para abrigo de paño. Aquí luego agregaremos foto real, color, medidas y detalles.",
        "destacado": false
    },
    {
        "id": 32,
        "nombre": "Blazer Largo 32",
        "tipo": "Blazer Largo",
        "talla": "S",
        "estado": "Excelente estado",
        "precio": 50000,
        "disponibilidad": "Disponible",
        "imagen": "",
        "descripcion": "Espacio reservado para blazer largo. Aquí luego agregaremos foto real, color, medidas y detalles.",
        "destacado": false
    },
    {
        "id": 33,
        "nombre": "Abrigo Peludo 33",
        "tipo": "Abrigo Peludo",
        "talla": "M",
        "estado": "Muy buen estado",
        "precio": 51000,
        "disponibilidad": "Disponible",
        "imagen": "",
        "descripcion": "Espacio reservado para abrigo peludo. Aquí luego agregaremos foto real, color, medidas y detalles.",
        "destacado": false
    },
    {
        "id": 34,
        "nombre": "Abrigo de Lana 34",
        "tipo": "Abrigo de Lana",
        "talla": "L",
        "estado": "Buen estado",
        "precio": 52000,
        "disponibilidad": "Disponible",
        "imagen": "",
        "descripcion": "Espacio reservado para abrigo de lana. Aquí luego agregaremos foto real, color, medidas y detalles.",
        "destacado": false
    },
    {
        "id": 35,
        "nombre": "Trench Coat 35",
        "tipo": "Trench Coat",
        "talla": "XL",
        "estado": "Por revisar",
        "precio": null,
        "disponibilidad": "Reservado",
        "imagen": "",
        "descripcion": "Espacio reservado para trench coat. Aquí luego agregaremos foto real, color, medidas y detalles.",
        "destacado": true
    }
];

// Se expone la lista para que script.js pueda usarla.
window.productosBeaGi = productosBeaGi;
